### ISSUE TITLE
Add selected/unselected in events

### ISSUE THREAD

**Issue by FerrozPro** [Js41637/Overwatch-Item-Tracker#224] opened 2018-05-23 13:10 UTC
Hi, is it possibile to add a fileter in every event where there is the possibility to show only selected/unselected item of that event?

**Comment by Js41637** [comment] 2018-05-23 19:47
Yeah something I still need to figure out how to do.

This is a dupe of #146 though so i'm closing it.

**Closed by Js41637** 2018-05-23 19:47 UTC
